<div x-data="{
    privateData: null,
    init() {
        if (window.hyva?.privateContent?.data) {
            this.privateData = window.hyva.privateContent.data
        } else {
            window.addEventListener('private-content-loaded',
                e => this.privateData = e.detail.data
            )
        }

        this.$watch('privateData', value => {
            if (value) {
                getresponseRecommendationHyva(value?.['getresponse-recommendation'])
            }
        })
    }
}">
</div>
</div>
<script>
    function getresponseRecommendationHyva(data) {
        const { getResponseShopId, productIdAddedToWishList, productIdRemovedFromWishList } = data

            if (productIdAddedToWishList !== null && productIdRemovedFromWishList === null) {
                const likeItemObject = {
                    shop: {id: getResponseShopId},
                    product: {id: productIdAddedToWishList}
                };
                GrTracking('importScript', 'ec');
                GrTracking('likeItem', likeItemObject);
            }

            if (productIdRemovedFromWishList !== null && productIdAddedToWishList === null) {
                const unlikeItemObject = {
                    shop: {id: getResponseShopId},
                    product: {id: productIdRemovedFromWishList}
                };
                GrTracking('importScript', 'ec');
                GrTracking('unlikeItem', unlikeItemObject);
            }

    }
</script>