<div class="getresponse-recommendation-section" data-bind="scope: 'getresponse_recommendation_section'">
    <div id="getresponse-recommendation" data-bind="attr: {
        'getresponse-shop-id': getResponseRecommendation() && getResponseRecommendation().getResponseShopId,
        'product-id-added-to-wishlist': getResponseRecommendation() && getResponseRecommendation().productIdAddedToWishList,
        'product-id-removed-from-wishlist': getResponseRecommendation() &&  getResponseRecommendation().productIdRemovedFromWishList
    }"></div>
</div>

<script>
    require(['Magento_Customer/js/customer-data'], function (customerData) {

        const recommendationNode = document.getElementById('getresponse-recommendation');
        const recommendation = document.querySelector('#getresponse-recommendation');

        const recommendationObserver = new MutationObserver(function(mutations) {

            const getResponseShopId = recommendationNode.getAttribute('getresponse-shop-id');
            const productIdAddedToWishList = recommendationNode.getAttribute('product-id-added-to-wishlist');
            const productIdRemovedFromWishList = recommendationNode.getAttribute('product-id-removed-from-wishlist');

            if (getResponseShopId === null) {
                return false;
            }

            if (productIdAddedToWishList !== null && productIdRemovedFromWishList === null) {
                const likeItemObject = {
                    shop: {id: getResponseShopId},
                    product: {id: productIdAddedToWishList}
                };
                GrTracking('importScript', 'ec');
                GrTracking('likeItem', likeItemObject);
                customerData.reload(['getresponse-recommendation']);
            }

            if (productIdRemovedFromWishList !== null && productIdAddedToWishList === null) {
                const unlikeItemObject = {
                    shop: {id: getResponseShopId},
                    product: {id: productIdRemovedFromWishList}
                };
                GrTracking('importScript', 'ec');
                GrTracking('unlikeItem', unlikeItemObject);
                customerData.reload(['getresponse-recommendation']);
            }

        });

        recommendationObserver.observe(recommendation, { attributes: true });
    });
</script>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "getresponse_recommendation_section": {
                        "component": "GetResponse_GetResponseIntegration/js/getresponse_recommendation_section"
                    }
                }
            }
        }
    }
</script>
