<?php

declare(strict_types=1);

use GetResponse\GetResponseIntegration\Block\Header;

/** @var Header $block */
$data = $block->getTrackingData();

if ('' !== $data['trackingCodeSnippet']) {
    echo $data['trackingCodeSnippet'];
}

if ('' !== $data['facebookPixelCodeSnippet']) {
    echo $data['facebookPixelCodeSnippet'];
}

if ('' !== $data['facebookAdsPixelCodeSnippet']) {
    echo $data['facebookAdsPixelCodeSnippet'];
}

if ('' !== $data['facebookBusinessExtensionCodeSnippet']) {
    echo $data['facebookBusinessExtensionCodeSnippet'];
}
