<?php
/** @var $block \GetResponse\GetResponseIntegration\Block\Header */
$data = $block->getTrackingData();
?>

<?php if ($data['isTrackingCodeEnabled']): ?>

    <?php echo $data['trackingCodeSnippet']; ?>

    <?php if (!empty($data['customerEmail'])): ?>
        <script type="text/javascript">
            if (window.addEventListener) {
                window.addEventListener("load", function () {
                    gaSetUserId("<?php echo $data['customerEmail']; ?>");
                })
            } else {
                window.attachEvent("onload", function () {
                    gaSetUserId("<?php echo $data['customerEmail']; ?>");
                })
            }
        </script>');
    <?php endif; ?>

<?php endif; ?>
