services:
  php72:
    container_name: magento-plugin-php72
    platform: linux/amd64
    build:
      context: .
      dockerfile: .docker/php72/Dockerfile
    environment:
      COMPOSER_HOME: /root/.composer
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
      - ~/.composer:/root/.composer
      - vendor-php72:/app/vendor
    secrets:
      - source: composer
        target: /root/.composer/auth.json
    command: sleep infinity

  php83:
    container_name: magento-plugin-php83
    platform: linux/amd64
    build:
      context: .
      dockerfile: .docker/php83/Dockerfile
    environment:
      COMPOSER_HOME: /root/.composer
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
      - ~/.composer:/root/.composer
      - vendor-php83:/app/vendor
    secrets:
      - source: composer
        target: /root/.composer/auth.json
    command: sleep infinity

volumes:
  vendor-php72:
  vendor-php83:

secrets:
  composer:
    file: ${COMPOSER_HOME}/auth.json