<?php /** @var $block \GetResponse\GetResponseIntegration\Block\Export */?>

<?php
if (!$block->checkApiKey()) {
    return;
}

$categories = $block->getStoreCategories();
$campaigns = $block->getCampaigns();
$autoresponders = $block->getAutoresponders();
$automations = $block->getAutomations()->getData();

?>

<div class="page-main-actions">
    <div class="page-main-hint">
        <span>Automatically move or copy your customers between your GetResponse contact lists when people purchase in Magento product category.</span>
    </div>
    <div class="page-actions">
        <div class="page-actions-inner">
            <div class="page-actions-buttons">
                <button id="getresponse_create_new_rule" onclick="location.href='<?php echo $block->getUrl('getresponseintegration/rules/create'); ?>'" title="Add New Rule" class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" type="button" role="button" aria-disabled="false">
                    <span class="ui-button-text">
                        <span>Add New Rule</span>
                    </span>
                </button>
            </div>
        </div>
    </div>
</div>
<div id="page:main-container" class="page-columns">
    <div class="admin__old">
        <div id="container" class="main-col">
            <div id="automation-table-wrap" class="admin__data-grid-wrap" data-role="grid-wrapper">
                <table class="data-grid" id="automation-table">
                    <thead>
                        <tr>
                            <th class="data-grid-th">
                                <span class="data-grid-cell-content">If customer buys in the category</span>
                            </th>

                            <th class="data-grid-th">
                                <span class="data-grid-cell-content">they are</span>
                            </th>

                            <th class="data-grid-th">
                                <span class="data-grid-cell-content">into the contact list</span>
                            </th>

                            <th class="data-grid-th">
                                <span class="data-grid-cell-content">Add to autoresponder cycle</span>
                            </th>
                            <th class="data-grid-th">
                                <span class="data-grid-cell-content">Autoresponder</span>
                            </th>

                            <th class="data-grid-th">
                                <span class="data-grid-cell-content">Action</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php if (empty($automations)): ?>
                        <tr>
                            <td colspan="6" class="no-data">
                                We couldn't find any records
                            </td>
                        </tr>
                        <?php else: ?>
                        <?php foreach ($automations as $automation): ?>
                            <tr class="data-row" data-role="data-grid-bulk-row">

                                <td class="category">
                                    <?php echo $block->getCategoryName($automation['category_id']); ?>
                                </td>

                                <td class="action">
                                    <?php echo $block->getAction($automation['action']); ?>
                                </td>

                                <td class="campaign">
                                    <?php $campaign = $block->getCampaign($automation['campaign_id']); ?>
                                    <?php echo isset($campaign->name) ? $campaign->name : ''; ?>
                                </td>

                                <td>
                                    <input type="checkbox" disabled="disabled"
                                           <?php echo (null !== $automation['cycle_day']) ? 'checked="checked"' : '' ?> />
                                </td>

                                <td class="cycle_day_edit">
                                    <?php if (isset($automation['cycle_day']) and $automation['cycle_day'] != ''):?>

                                    (Day: <?php echo $automation['cycle_day'] ?>)
                                    <?php  echo isset($autoresponders[$automation['campaign_id']][$automation['cycle_day']]) ? $autoresponders[$automation['campaign_id']][$automation['cycle_day']]['name'] : '' ?>
                            <?php endif ?>
                                </td>

                                <td>
                                    <a href="<?php echo $block->getUrl('getresponseintegration/rules/edit/', array('id' => $automation['id'])); ?>">Edit</a>
                                </td>

                            </tr>
                        <?php endforeach ?>
                    <?php endif ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<input type="hidden" id="jsAutoresponders" value='<?php echo json_encode($autoresponders); ?>'/>
<script>
    require(['automation']);
</script>