<?php
use GetResponse\GetResponseIntegration\Block\Lists;

/** @var Lists $block */
$from_fields = $block->getAccountFromFields();
$confirmation_subjects = $block->getSubscriptionConfirmationsSubject();
$confirmation_bodies = $block->getSubscriptionConfirmationsBody();
?>

<form id="createNewListForm" action="<?php echo $block->getUrl('getresponse/lists/create'); ?>" method="POST">
    <?php echo $block->getBlockHtml('formkey'); ?>
    <input type="hidden" name="back_url" value="<?php echo $block->getBackUrl()?>" />

    <div class="page-main-actions">
        <div class="page-main-hint"></div>
        <div class="page-actions">
            <div class="page-actions-inner">
                <div class="page-actions-buttons">
                    <button id="back" title="Back" class="action-default scalable back" role="button" type="button" aria-disabled="false" onclick="location.href='<?php echo $block->getUrl($block->getBackUrl())?>'">
                        <span class="ui-button-text">
                            <span>Back</span>
                        </span>
                    </button>
                    <button id="export" title="Save New List" type="submit" class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button" aria-disabled="false">
                        <span class="ui-button-text">
                            <span>Save New List</span>
                        </span>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div id="page:main-container" class="page-columns">
        <div class="admin__old">
            <div id="container" class="main-col">

                <fieldset class="fieldset admin__fieldset" id="campaign_name_fieldset">
                    <div class="admin__field field field-basic_campaign_name required _required with-note">
                        <label class="label admin__field-label" for="api_key">
                            <span>List name</span>
                        </label>
                        <div class="admin__field-control control">
                            <input name="campaign_name" id="campaign_name" value="" title="List name" class="basic_behavior input-text input-text admin__control-text required-entry _required" type="text" aria-required="true">
                            <div class="validation-message"></div>
                        </div>
                    </div>

                    <div class="admin__field field field-basic_from_field required _required with-note">
                        <label class="label admin__field-label" for="from_field">
                            <span>From field</span>
                        </label>
                        <div class="admin__field-control control">
                            <select name="from_field" id="from_field" class="select admin__control-select" aria-required="true">
                                <option value="">Select from field</option>
                                <?php
                                if (isset($from_fields)) {
                                    foreach ($from_fields as $from_field) {
                                        echo '<option value="' . $from_field->fromFieldId . '">' . $from_field->name . ' (' . $from_field->email . ')</option>';
                                    }
                                }
                                ?>
                            </select>
                            <div class="validation-message"></div>
                        </div>
                    </div>

                    <div class="admin__field field field-basic_reply_to_field required _required with-note">
                        <label class="label admin__field-label" for="reply_to_field">
                            <span>Reply-to</span>
                        </label>
                        <div class="admin__field-control control">
                            <select name="reply_to_field" id="reply_to_field" class="select admin__control-select" aria-required="true">
                                <option value="">Select reply-to address</option>
                                <?php
                                if (isset($from_fields)) {
                                    foreach ($from_fields as $from_field) {
                                        echo '<option value="' . $from_field->fromFieldId . '">' . $from_field->name . ' (' . $from_field->email . ')</option>';
                                    }
                                }
                                ?>
                            </select>
                            <div class="validation-message"></div>
                        </div>
                    </div>

                    <div class="admin__field field field-basic_confirmation_subject required _required with-note">
                        <label class="label admin__field-label" for="confirmation_subject">
                            <span>Confirmation subject</span>
                        </label>
                        <div class="admin__field-control control">
                            <select name="confirmation_subject" id="confirmation_subject" class="select admin__control-select" aria-required="true">
                                <option value="">Select confirmation message subject</option>
                                <?php
                                if (isset($confirmation_subjects)) {
                                    foreach ($confirmation_subjects as $subject) {
                                        echo '<option value="' . $subject->subscriptionConfirmationSubjectId . '">' . $subject->subject . '</option>';
                                    }
                                }
                                ?>
                            </select>
                            <div class="validation-message"></div>
                        </div>
                    </div>

                    <div class="admin__field field field-basic_confirmation_body required _required with-note">
                        <label class="label admin__field-label" for="confirmation_body">
                            <span>Confirmation body</span>
                        </label>
                        <div class="admin__field-control control">
                            <select name="confirmation_body" id="confirmation_body" class="select admin__control-select" aria-required="true">
                                <option value="">Select confirmation message body template</option>
                                <?php
                                    if (isset($confirmation_bodies)) {
                                        foreach ($confirmation_bodies as $body) {
                                            echo '<option value="' . $body->subscriptionConfirmationBodyId . '">(' . $body->name . ') ' . $body->contentPlain . '</option>';
                                        }
                                    }
                                ?>
                            </select>
                            <div class="validation-message"></div>
                            <div class="note admin__field-note" id="gr_sync_order_data-note">
                                The confirmation message body and subject depend on System >> Configuration >> General >> Locale Options.
                            </div>
                            <div class="note admin__field-note" id="gr_sync_order_data-note">
                                By default all lists you create in Magento have double opt-in enabled. You can change this later in your <a href="https://support.getresponse.com/faq/how-i-disable-confirmation-message" target="_blank">list settings</a>.
                            </div>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
    </div>
</form>

<script>
    require(['createList']);
</script>