<?php
$customs = $block->getDefaultCustoms()->getData();
$customNum = 3;
?>
<div class="admin__data-grid-header admin__data-grid-toolbar">
    <button id="addNewMappingBtn" title="Add new mapping" type="button" class="action- scalable action-secondary">
        <span>Add new mapping</span>
    </button>
</div>
<div class="admin__data-grid-wrap admin__data-grid-wrap-static">
    <table class="data-grid" data-role="grid">
        <thead>
        <tr>
            <th class="data-grid-th _draggable">
                <span class="data-grid-cell-content">Customer details</span>
            </th>
            <th class="data-grid-th _draggable _ascend">
                <span class="data-grid-cell-content">Custom fields in GetResponse</span>
            </th>
            <th class="data-grid-th">
                <span class="data-grid-cell-content">Action</span>
            </th>
        </tr>
        </thead>
        <tbody id="customsDataBody">
        <?php if (count($customs) > 0): ?>
            <?php foreach ($customs as $key => $custom): ?>
                <?php if ($custom['active_custom'] == 1): ?>
                    <tr class="data-row <?php if ($key % 2): ?>_odd-row<?php endif ?>">
                        <td>
                            <div class="data-grid-cell-content">
                                <select
                                    <?php if ($custom['default'] == 1): ?>disabled<?php endif ?>
                                    name="custom[]">
                                    <?php foreach ($customs as $_custom): ?>
                                        <option
                                            <?php if ($_custom['id'] === $custom['id']): ?>selected="selected"<?php endif ?>
                                            value="<?php echo $_custom['custom_field'] ?>"><?php echo $_custom['custom_value'] ?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                        </td>
                        <td>
                            <div class="data-grid-cell-content">
                                <input
                                    <?php if ($custom['default'] == 1): ?>disabled<?php endif ?>
                                    type="text" name="gr_custom[]" value="<?php echo $custom['custom_name'] ?>">
                            </div>
                        </td>
                        <td>
                            <div class="data-grid-cell-content">
                                <?php if ($custom['default'] != 1): ?>
                                    <a href="#" class="deleteCustomBtn">Delete</a>
                                <?php endif ?>
                            </div>
                        </td>
                    </tr>
                <?php endif ?>
            <?php endforeach ?>
        <?php endif ?>
        </tbody>
    </table>
</div>
<input type="hidden" id="jsCustoms" value='<?php echo json_encode($customs); ?>'/>
<script>
    require(['customsGrid']);
</script>