<style>
    .page-main-hint {
        float: left;
    }

    .page-main-hint span {
        display: inline-block;
        margin-top: 1rem;
    }

    .hidden {
        display: none;
    }
</style>

<?php /** @var $block \GetResponse\GetResponseIntegration\Block\Ecommerce */

$shops = $block->getShops();
$shopStatus = $block->getShopStatusFromConfig();
$currentShopId = $block->getCurrentShopId();
$settings = $block->getSettings();
?>

<form method="post" action="<?php echo $block->getUrl('getresponseintegration/ecommerce/saveshop'); ?>">
    <?php echo $block->getBlockHtml('formkey'); ?>

    <div class="page-main-actions">
        <div class="page-main-hint">
            <span>GetResponse helps you track and collect ecommerce data. You can stay informed about customers’ behavior and spending habits.<br/>Use this data to create marketing automation workflows that react to purchases, abandoned carts, or the amounts of money spent.</span>
        </div>
        <div class="page-actions">
            <div class="page-actions-inner">
                <div class="page-actions-buttons">
                    <?php if (isset($settings['active_subscription']) && $settings['active_subscription'] == 1): ?>
                        <button title="Export" type="submit"
                                class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"
                                role="button" aria-disabled="false">
                        <span class="ui-button-text">
                            <span>Save</span>
                        </span>
                        </button>
                    <?php endif ?>
                </div>
            </div>
        </div>
    </div>
    <div id="page:main-container" class="page-columns">
        <div class="admin__old">
            <div id="container" class="main-col">
                <?php if (isset($settings['active_subscription']) && $settings['active_subscription'] == 0): ?>
                    <div id="messages">
                        <div class="messages">
                            <div class="message message-notice notice">
                                <div data-ui-id="messages-message-notice">
                                    Make sure to enable adding contacts during registration to start sending ecommerce
                                    data to GetResponse
                                </div>
                            </div>
                        </div>
                    </div>
                <?php else: ?>
                    <fieldset class="fieldset admin__fieldset" id="gr_enabled_fieldset">
                        <div class="admin__field field field-basic_e_commerce_status required _required">
                            <label class="label admin__field-label" for="e_commerce_status"></label>
                            <div class="admin__field-control control">
                                <div class="admin__field admin__field-option e_commerce_status__field">
                                    <input id="e_commerce_status" name="e_commerce_status"
                                           class="admin__control-checkbox" type="checkbox" value="1"
                                        <?php if ('enabled' === $shopStatus): ?> checked="checked" <?php endif ?>
                                    />
                                    <label class="admin__field-label" for="e_commerce_status">Send ecommerce data to
                                        GetResponse</label>
                                </div>
                            </div>
                        </div>
                        <div class="admin__field field field-basic_campaign required _required forms addNewShopRow
                            <?php if ('disabled' === $shopStatus): ?>hidden<?php endif ?>">
                            <label class="label admin__field-label" for="shop_id">
                                <span>Store</span>
                            </label>
                            <div class="admin__field-control control">
                                <div class="admin__field">
                                    <select name="shop_id" id="shop_id" class="select admin__control-select"
                                            aria-required="true">
                                        <option value="">Select a store</option>
                                        <?php foreach ($shops as $shop): ?>
                                            <option
                                                <?php if ($shop->shopId === $currentShopId): ?> selected="selected" <?php endif ?>
                                                    value="<?php echo $shop->shopId ?>">
                                                <?php echo $shop->name ?>
                                            </option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </fieldset>

                    <div class="addNewShopRow <?php if ('disabled' === $shopStatus): ?>hidden<?php endif ?>">

                        <h2>Store list</h2>

                        <div class="admin__data-grid-header admin__data-grid-toolbar">
                            <button id="addNewStoreBtn" title="Add New Store" class="action- scalable action-secondary" type="button">
                                <span class="ui-button-text">
                                    <span>Add New Store</span>
                                </span>
                            </button>
                        </div>
                        <input type="hidden" name="enableGrEcommerce" value="1"/>
                        <div class="admin__data-grid-wrap admin__data-grid-wrap-static">
                            <table class="data-grid" data-role="grid">
                                <thead>
                                <tr>
                                    <th class="data-grid-th">
                                        <span class="data-grid-cell-content">Store name</span>
                                    </th>
                                    <th class="data-grid-th">
                                        <span class="data-grid-cell-content">Action</span>
                                    </th>
                                </tr>
                                </thead>
                                <tbody id="storesDataBody">
                                    <?php if (count($shops) > 0): ?>
                                        <?php foreach ($shops as $key => $shop): ?>
                                            <tr class="data-row <?php if ($key % 2): ?>_odd-row<?php endif ?>">
                                                <td>
                                                    <?php echo $shop->name ?>
                                                </td>
                                                <td>
                                                    <a href="#" data-id="<?php echo $shop->shopId ?>" class="deleteStoreBtn">Delete</a>
                                                </td>
                                            </tr>
                                        <?php endforeach ?>
                                    <?php endif ?>
                                </tbody>
                            </table>
                        </div>
                    </div>

                <?php endif ?>
            </div>
        </div>
    </div>
</form>

<div id="popup-modal" style="display: none;">
    <div>Please confirm that you want to delete this store.</div>
</div>

<script>
    require(['jquery'],function($) {
        var isAddingStore = false;
        var storesNumber = $('.data-row').length;

        var ecommerceStatusCheckbox = $('#e_commerce_status');
        var addNewShopRow = $('.addNewShopRow');

        ecommerceStatusCheckbox.change(function () {
            addNewShopRow.toggleClass('hidden');
        });

        $(document).on('click', '.deleteStoreBtn', function (e) {
            e.preventDefault();

            var shopId = $(this).attr('data-id');

            showDeleteStoreConfirm(shopId);
        });

        $('#addNewStoreBtn').on('click', function () {
            if (!isAddingStore) {
                addEditableStoreRow();
            }
        });

        $(document).on('click', '.confirmStoreBtn', function () {
            var shopName = $(this).parent().parent().parent().find('.storeName').val();

            $.ajax({
                type: "POST",
                url: '<?php echo $block->getUrl('getresponseintegration/ecommerce/createshop'); ?>?isAjax=true',
                data: {
                    form_key: FORM_KEY,
                    shop_name: shopName
                },
                success: function (data) {
                    var json = jQuery.parseJSON(data);

                    if (json.error) {
                        // tutaj trzeba dodać notyfikację dla klienta o błędzie!
                        return false;
                    }

                    removeEditStoreRow();
                    addStoreRow(json);
                },
                error: function () {
                    removeEditStoreRow();
                }
            })
        });

        function removeEditStoreRow() {
            isAddingStore = false;
            $(".data-row").last().remove();
            toggleDisableAddNewStoreBtn(isAddingStore);
        }

        function addStoreRow(data) {
            isAddingStore = false;
            var isOddRow = storesNumber % 2 === 0 ? '' : '_odd-row';
            var newStore = '<tr class="data-row ' + isOddRow + '">' +
                '<td>' +
                '<div class="data-grid-cell-content">' +
                data.name +
                '</div>' +
                '</td>' +
                '<td>' +
                '<div class="data-grid-cell-content">' +
                '<a href="#" data-id="' + data.shopId + '" class="deleteStoreBtn">Delete</a>' +
                '</div>' +
                '</td>' +
                '</tr>';

            $('#storesDataBody').append(newStore);
            updateStoreSelect(data);
            toggleDisableAddNewStoreBtn(isAddingStore);
        }

        function addEditableStoreRow() {
            isAddingStore = true;
            var isOddRow = storesNumber % 2 === 0 ? '' : '_odd-row';
            var newStore = '<tr class="data-row ' + isOddRow + '">' +
                '<td>' +
                '<div class="data-grid-cell-content">' +
                '<input type="text" class="storeName">' +
                '</div>' +
                '</td>' +
                '<td>' +
                '<div class="data-grid-cell-content">' +
                '<a href="#" class="confirmStoreBtn">Confirm</a>' +
                '</div>' +
                '</td>' +
                '</tr>';

            $('#storesDataBody').append(newStore);
            focusEditStoreNameInput();
            toggleDisableAddNewStoreBtn(isAddingStore);
        }

        function focusEditStoreNameInput() {
            $(".data-row").last().find('.storeName').focus();
        }

        function toggleDisableAddNewStoreBtn(isAddingStore) {
            if (isAddingStore) {
                $('#addNewStoreBtn').attr('disabled', 'disabled');
            } else {
                $('#addNewStoreBtn').removeAttr('disabled');
            }
        }

        function updateStoreSelect(data) {
            var newStoreOption = '<option value="' + data.shopId + '">' + data.name + '</option>';

            $('#shop_id').append(newStoreOption);
        }

        function showDeleteStoreConfirm(shopId) {
            require(
                ['jquery', 'Magento_Ui/js/modal/modal'],
                function ($, modal) {
                    var url = '<?php echo $block->getUrl('getresponseintegration/ecommerce/delete'); ?>' + '?id=' + shopId;
                    var options = {
                        type: 'popup',
                        responsive: true,
                        innerScroll: true,
                        title: 'Delete store',
                        buttons: [
                            {
                                text: $.mage.__('Cancel'),
                                class: 'action-secondary action-dismiss',
                                click: function () {
                                    this.closeModal();
                                }
                            }, {
                                text: $.mage.__('Delete'),
                                class: 'action-primary action-accept',
                                click: function () {
                                    window.location.href = url;
                                    return false;
                                }
                            },
                        ]
                    };

                    var popup = modal(options, $('#popup-modal'));
                    $('#popup-modal').modal('openModal');
                }
            )
        }
    });

</script>