<?php
/** @var GetResponse\GetResponseIntegration\Block\Rules $block */
/** @var \GetResponse\GetResponseIntegration\Domain\GetResponse\Rule $rule */
$rule = $block->getCurrentRule();
$categories = $block->getStoreCategories();
$campaigns = $block->getCampaigns();
$jsAutoresponders = $block->getAutorespondersForFrontend();
?>
<form id="editRuleForm" action="" method="POST">
    <?php echo $block->getBlockHtml('formkey'); ?>
    <div class="page-main-actions">
        <div class="page-actions-placeholder" style=""></div>
        <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
            <div class="page-actions-inner" data-title="New Customer">
                <div class="page-actions-buttons">
                    <button id="back" title="Back" type="button" class="action- scalable back"
                            onclick="location.href = '<?php echo $block->getUrl('getresponseintegration/settings/automation'); ?>'"
                            data-ui-id="back-button">
                        <span>Back</span>
                    </button>

                    <button title="Delete Rule" type="button" id="deleteRuleBtn" class="action-delete scalable">
                        <span>Delete</span>
                    </button>

                    <button id="save" title="Save Rule" type="submit"
                            class="action- scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"
                            data-form-role="save" data-ui-id="save-button" role="button" aria-disabled="false">
                        <span class="ui-button-text"><span>Save Rule</span></span></button>
                </div>
            </div>
        </div>
    </div>

    <div id="page:main-container" class="page-columns">
        <div class="admin__old">
            <div id="container" class="main-col">

                <fieldset class="admin__fieldset">
                    <div class="admin__field _required">
                        <label class="admin__field-label">
                            <span>If customer buys in the category</span>
                        </label>
                        <div class="admin__field-control _with-tooltip">
                            <select name="category" id="category" class="admin__control-select">
                                <option value="">Select a category</option>
                                <?php if (!empty($categories)): ?>
                                    <?php foreach ($categories as $category): ?>
                                        <option
                                            <?php if ($category->getEntityId() == $rule->getCategory()): ?>selected="selected"<?php endif ?>
                                            value="<?php echo $category->getEntityId() ?>"><?php echo $category->getName() ?></option>
                                        <?php echo $block->getSubcategories($category, $rule->getCategory()) ?>
                                    <?php endforeach ?>
                                <?php endif ?>
                            </select>
                            <div class="validation-message"></div>
                        </div>
                    </div>

                    <div class="admin__field _required">
                        <label class="admin__field-label">
                            <span>They are</span>
                        </label>
                        <div class="admin__field-control _with-tooltip">
                            <select name="action" id="action" class="admin__control-select">
                                <option value="">They are</option>
                                <option
                                    <?php if ($rule->getAction() == 'move'): ?>selected="selected"<?php endif ?>
                                    value="move">moved
                                </option>
                                <option
                                    <?php if ($rule->getAction() == 'copy'): ?>selected="selected"<?php endif ?>
                                    value="copy">copied
                                </option>
                            </select>
                            <div class="validation-message"></div>
                        </div>
                    </div>

                    <div class="admin__field _required">
                        <label class="admin__field-label">
                            <span>Into the contact list</span>
                        </label>
                        <div class="admin__field-control _with-tooltip">
                            <select name="campaign" id="campaign_id" class="admin__control-select">
                                <option value="">Into the contact list</option>
                                <?php if (count($campaigns) > 0): ?>
                                    <?php foreach ($campaigns as $campaign): ?>
                                        <option
                                            <?php if ($campaign->campaignId == $rule->getCampaign()): ?>selected="selected"<?php endif ?>
                                            value="<?php echo $campaign->campaignId ?>">
                                            <?php echo $campaign->name ?>
                                        </option>
                                    <?php endforeach ?>
                                <?php endif ?>
                            </select>
                            <div class="validation-message"></div>
                        </div>
                    </div>

                    <div class="admin__field field field-basic_autoresponder forms">
                        <label class="label admin__field-label" for="gr_enabled"></label>
                        <div class="admin__field-control control">
                            <div class="admin__field admin__field-option gr_enabled__field">
                                <input class="admin__control-checkbox"
                                       type="checkbox"
                                       name="gr_autoresponder"
                                       id="gr_autoresponder"
                                       value="1"
                                    <?php
                                    if (!empty($rule->getAutoresponder())) {
                                        echo ' checked="checked"';
                                    }
                                    ?>
                                />
                                <label class="admin__field-label" for="gr_autoresponder">Add to autoresponder cycle</label>
                            </div>
                        </div>
                    </div>
                    <div class="admin__field field field-basic_autoresponder forms">
                        <label class="label admin__field-label" for="cycle_day">
                            <span>Autoresponder day</span>
                        </label>
                        <div class="admin__field-control control">
                            <div class="admin__field cycle_day">
                                <select name="cycle_day" id="cycle_day" class="select admin__control-select" aria-required="true" disabled="disabled"></select>
                                <input type="hidden" name="selected_cycle_day" value="<?php echo $rule->getAutoresponder() ?>" />
                            </div>
                        </div>
                    </div>

                </fieldset>
            </div>
        </div>
    </div>
</form>

<div id="popup-modal" style="display: none;">
    <div>Please confirm that you want to delete this rule.</div>
</div>

<script>
    require(['jquery'],function($) {
        var editRuleForm = $('#editRuleForm');
        var category = editRuleForm.find('#category');
        var action = editRuleForm.find('#action');
        var campaign_id = editRuleForm.find('#campaign_id');

       var cycle_day = jQuery('#cycle_day');
       var gr_autoresponder = jQuery('#gr_autoresponder');
       var deleteRuleBtn = jQuery('#deleteRuleBtn');
       var autoresponders = <?php echo json_encode($jsAutoresponders); ?>;

        editRuleForm.submit(function () {
            return isFormValid();
        });

        function isFormValid() {
            validateIfEmptyField(category);
            validateIfEmptyField(action);
            validateIfEmptyField(campaign_id);

            return !!validateIfEmptyField(category) && !!validateIfEmptyField(action) && !!validateIfEmptyField(campaign_id);
        }

        function validateIfEmptyField(field) {
            if (field.val() === '') {
                showEmptyErrorMessage(field);
                return false;
            } else {
                clearErrorMessage(field);
                return true;
            }
        }

        function showEmptyErrorMessage(field) {
            var errorMessage = null;

            switch (field.attr('id')) {
                case 'category':
                    errorMessage = 'You need to select your product category';
                    break;
                case 'action':
                    errorMessage = 'You need to select what to do with the customer';
                    break;
                case 'campaign_id':
                    errorMessage = 'You need to select a target list';
            }

            appendError(field, errorMessage);
        }

        function appendError(field, errorMessage) {
            field.next().html('<label class="admin__field-error">' + errorMessage + '</label>');
            field.parent().parent().addClass('_error');
        }

        function clearErrorMessage(field) {
            field.next().html('');
            field.parent().parent().removeClass('_error');
        }

        function populateSelectWithAutoresponders() {
            cycle_day.empty();
            var options = '';
            var campaign_autoresponders = autoresponders[campaign_id.val()];
            if (typeof campaign_autoresponders == 'object' && campaign_autoresponders.length > 0) {
                for (var i = 0; i < campaign_autoresponders.length; i++) {
                    options += '<option value="' + campaign_autoresponders[i]['dayOfCycle']
                        + '">(Day: ' + campaign_autoresponders[i]['dayOfCycle'] + ') '
                        + campaign_autoresponders[i]['name']
                        + ' (Subject: ' + campaign_autoresponders[i]['subject'] + ')</option>';
                }
                cycle_day.prop('disabled', false);
                gr_autoresponder.prop('disabled', false);
            } else {
                options = '<option value="">no autoresponders</option>';
                cycle_day.prop('disabled', true);
                gr_autoresponder.prop('disabled', true).prop('checked', false);
            }
            cycle_day.append(options);
        }

        populateSelectWithAutoresponders();

        campaign_id.change(function () {
            populateSelectWithAutoresponders();
        });

        deleteRuleBtn.on('click', openDeleteRuleConfirm);

        function openDeleteRuleConfirm() {
            require(
                ['jquery', 'Magento_Ui/js/modal/modal'],
                function ($, modal) {
                    var url = '<?php echo $block->getUrl('getresponseintegration/rules/delete',
                        ['id' => $rule->getId()]); ?>';
                    var options = {
                        type: 'popup',
                        responsive: true,
                        innerScroll: true,
                        title: 'Delete rule',
                        buttons: [
                            {
                                text: $.mage.__('Cancel'),
                                class: 'action-secondary action-dismiss',
                                click: function () {
                                    this.closeModal();
                                }
                            }, {
                                text: $.mage.__('Delete'),
                                class: 'action-primary action-accept',
                                click: function () {
                                    window.location.href = url;
                                    return false;
                                }
                            },
                        ]
                    };

                    var popup = modal(options, $('#popup-modal'));
                    $('#popup-modal').modal('openModal');
                }
            )
        }
    });

</script>