<?php
$from_fields = $block->getAccountFromFields();
$lang = substr($block->getStoreLanguage(), 0, 2);
$confirmation_subjects = $block->getSubscriptionConfirmationsSubject($lang);
$confirmation_bodies = $block->getSubscriptionConfirmationsBody($lang);
?>

<div id="popup-mpdal" class="modal config admin__scope-old" style="width: 300px; display: none;">
    <style>
        .campaign_value {
            /*border: 8px solid #EB5202;*/
            padding-left: 0px;
        }
    </style>
    <tr class="add_campaign_row" style="display:none;">
        <td class="value campaign_value">
            <p class="note">
            <span style="font-weight: bold;">
                Campaign name
            </span>
            </p>
            <input type="text" name="campaign_name" id="campaign_name" style="width: 500px;" />
            <span id="gr_spinner" style="display:none;"><img src="<?php echo $block->getViewFileUrl('GetResponse_GetResponseIntegration::images/ajax-loader-small.gif'); ?>" /></span>
            <p id="new_campaign_message" style="width: 600px;"></p>
        </td>
    </tr>

    <tr class="add_campaign_row" style="display:none;">
        <td class="value campaign_value">
            <p class="note">
            <span style="font-weight: bold;">
                From field
            </span>
            </p>
            <select name="from_field" id="from_field" style="width: 500px;">
                <?php
                if (isset($from_fields)) {
                    foreach ($from_fields as $from_field) {
                        echo '<option value="' . $from_field->fromFieldId . '">' . $from_field->name . ' (' . $from_field->email . ')</option>';
                    }
                }
                ?>
            </select>
        </td>
    </tr>

    <tr class="add_campaign_row" style="display:none;">
        <td class="value campaign_value">
            <p class="note">
            <span style="font-weight: bold;">
                Reply-To
            </span>
            </p>
            <select name="reply_to_field" id="reply_to_field" style="width: 500px;">
                <?php
                if (isset($from_fields)) {
                    foreach ($from_fields as $from_field) {
                        echo '<option value="' . $from_field->fromFieldId . '">' . $from_field->name . ' (' . $from_field->email . ')</option>';
                    }
                }
                ?>
            </select>
        </td>
    </tr>

    <tr class="add_campaign_row" style="display:none;">

        <td class="value campaign_value">
            <p class="note">
            <span style="font-weight: bold;">
                Confirmation subject
            </span>
            </p>
            <select name="confirmation_subject" id="confirmation_subject" style="width: 500px;">
                <?php
                if (isset($confirmation_subjects)) {
                    foreach ($confirmation_subjects as $subject) {
                        echo '<option value="' . $subject->subscriptionConfirmationSubjectId . '">' . $subject->subject . '</option>';
                    }
                }
                ?>
            </select>
        </td>
    </tr>

    <tr class="add_campaign_row" style="display:none;">

        <td class="value campaign_value">
            <p class="note">
            <span style="font-weight: bold;">
                Confirmation body
            </span>
            </p>
            <select name="confirmation_body" id="confirmation_body" style="width: 500px;" class="gr_select hiddenselect fullSelectHide">
                <?php
                if (isset($confirmation_bodies)) {
                    foreach ($confirmation_bodies as $body) {
                        echo '<option value="' . $body->subscriptionConfirmationBodyId . '">(' . $body->name . ') ' . $body->contentPlain . '</option>';
                    }
                }
                ?>
            </select>
            <p class="note" style="width: 750px; ">
                <span>
                    The confirmation message body and subject depend on System >> Configuration >> General >> Locale Options.
                </span>
            </p>
        </td>
    </tr>

    <p class="note" style="width: 750px; margin-top: 15px;">
        <span>
        By default all campaigns you create from Magento have double opt-in enabled. You can change this later in your <a href="https://support.getresponse.com/faq/how-i-disable-confirmation-message" target="_blank">campaign settings</a>.
        </span>
    </p>
</div>

<script type="text/javascript">
    function confirmationOpened() {

        require(
            [
                'jquery',
                'Magento_Ui/js/modal/modal'
            ],
            function ($, modal) {
                var add_campaign_rows = jQuery('.add_campaign_row');
                var popop_modal = jQuery('#popup-mpdal');
                var url = '<?php echo $block->getUrl('getresponseintegration/settings/createcampaign'); ?>?isAjax=true';

                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    title: 'Create new campaign',
                    buttons: [
                        {
                            text: $.mage.__('Create campaign'),
                            class: 'action-primary action-accept',
                            click: function () {
                                var regex = /^[a-z0-9_]{3,64}$/;
                                var campaign_name = popop_modal.find('#campaign_name').val();

                                if (campaign_name == '') {
                                    popop_modal.find('#new_campaign_message').html('<span style="color:red;">The campaign name can\'t be empty.</span>');
                                } else if (regex.test(campaign_name)) {
                                    jQuery.ajax({
                                        type: "POST",
                                        url: url,
                                        data: {
                                            form_key: FORM_KEY,
                                            campaign_name: campaign_name,
                                            from_field: popop_modal.find('#from_field').val(),
                                            reply_to_field: popop_modal.find('#reply_to_field').val(),
                                            confirmation_subject: popop_modal.find('#confirmation_subject').val(),
                                            confirmation_body: popop_modal.find('#confirmation_body').val()
                                        },
                                        beforeSend: function () {
                                            popop_modal.find('#new_campaign_message').html('');
                                            popop_modal.find("#gr_spinner").show();
                                        },
                                        success: function (data) {
                                            var json = jQuery.parseJSON(data);
                                            if (!json.campaignId) {
                                                var msg = 'An error occured:' + json.message;
                                                if (json.code == 1008) {
                                                    msg = 'The campaign name you entered already exists. Please enter a different name.';
                                                }
                                                popop_modal.find('#new_campaign_message').html('<span style="color:red;">' + msg + '</span>');
                                            } else {
                                                popop_modal.find('#campaign_name').val('');
                                                popop_modal.find('#new_campaign_message').html('');
                                                add_campaign_rows.hide('slow');
                                                jQuery('#campaign_id').append('<option value="' + json.campaignId + '" selected="selected">' + json.name + '</option>');
                                                popop_modal.find('#new_campaign_message').html('');
                                                $('#popup-mpdal').modal('closeModal');
                                            }
                                        },
                                        error: function (data) {
                                            popop_modal.find('#new_campaign_message').html('<span style="color:red;">An error occured</span>');
                                        },
                                        complete: function () {
                                            popop_modal.find("#gr_spinner").hide();
                                        }
                                    })
                                } else {
                                    popop_modal.find('#new_campaign_message').html('<span style="color:red;">Campaign name may consist only a-z (lower case), numbers and "_"</span>');
                                }
                            }
                        },
                        {
                            text: $.mage.__('Cancel'),
                            class: 'action-secondary action-dismiss',
                            click: function () {
                                popop_modal.find('#new_campaign_message').html('');
                                this.closeModal();
                            }
                        }
                    ]
                };

                var popup = modal(options, popop_modal);
                popop_modal.modal('openModal');
            }
        );
    }
</script>