<?php /** @var $block \GetResponse\GetResponseIntegration\Block\Settings */?>

<?php
if (!$block->checkApiKey()) {
    return;
}

$forms = $block->getAllFormsFromGr();
$settings = $block->getWebformSettings();

?>

<form method="post" action="<?php echo $block->getUrl('getresponseintegration/settings/webformpost'); ?>">
    <?php echo $block->getBlockHtml('formkey'); ?>

    <div class="page-main-actions">
        <div class="page-main-hint">
            <span>Add forms (or exit popups) to your store. Get new contacts when your customers fill them out.</span>
        </div>
        <div class="page-actions">
            <div class="page-actions-inner">
                <div class="page-actions-buttons">
                    <button id="export" title="Export" type="submit" class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button" aria-disabled="false">
                        <span class="ui-button-text">
                            <span>Save</span>
                        </span>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div id="page:main-container" class="page-columns">
        <div class="admin__old">
            <div id="container" class="main-col">
                <fieldset class="fieldset admin__fieldset no-display" id="publish_fieldset" style="display: block;">
                    <div class="admin__field field field-basic_publish required _required">
                        <label class="label admin__field-label" for="publish"></label>
                        <div class="admin__field-control control">
                            <div class="admin__field admin__field-option publish__field">
                                <input id="publish" name="publish" class="admin__control-checkbox" type="checkbox" value="1"
                                    <?php if (isset($settings['active_subscription']) && $settings['active_subscription'] == 1):?>
                                        checked="checked"
                                    <?php endif ?>
                                >
                                <label class="admin__field-label" for="publish">Add contacts to GetResponse via forms (or exit popups)</label>
                            </div>
                        </div>
                    </div>
                    <div class="admin__field field field-basic_webform required _required forms <?php if (!isset($settings['update']) || (int) $settings['update'] === 0):?>hidden<?php endif ?>">
                        <label class="label admin__field-label" for="webform_id">
                            <span>Form</span>
                        </label>
                        <div class="admin__field-control control">
                            <div class="admin__field">
                                <select name="webform_id" id="webform_id" class="select admin__control-select" aria-required="true">
                                    <option value="">Select a form you want to display</option>
                                    <?php if (!empty($forms['forms']) || !empty($forms['webforms'])):?>
                                        <?php if (isset($forms['forms']) && count($forms['forms']) > 0): ?>
                                            <?php foreach ($forms['forms'] as $form): ?>
                                                <option
                                                    value="<?php echo $form->webformId?>"
                                                    data-url="<?php echo $form->scriptUrl?>"
                                                    <?php if(isset($settings['webform_id']) && $settings['webform_id'] == $form->webformId):?>
                                                        selected="selected"
                                                    <?php endif ?>
                                                ><?php echo $form->name ?></option>
                                            <?php endforeach ?>
                                        <?php endif ?>

                                        <?php if (!empty($forms['webforms'])): ?>
                                            <option value="" disabled="disabled">Old Web Forms:</option>
                                            <?php foreach ($forms['webforms'] as $form): ?>
                                                <option
                                                    value="<?php echo $form->webformId?>"
                                                    data-url="<?php echo $form->scriptUrl?>"
                                                    <?php if(isset($settings['webform_id']) && $settings['webform_id'] == $form->webformId):?>
                                                        selected="selected"
                                                    <?php endif ?>
                                                ><?php echo $form->name ?></option>
                                            <?php endforeach ?>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <option value="" disabled="disabled">No forms</option>
                                    <?php endif ?>
                                </select>
                                <input type="hidden" value="" name="webform_url" id="webform_url" />
                            </div>
                        </div>
                    </div>
                    <div class="admin__field field field-basic_sidebar required _required forms <?php if (!isset($settings['update']) || (int) $settings['update'] === 0):?>hidden<?php endif ?>">
                        <label class="label admin__field-label" for="sidebar">
                            <span>Block position</span>
                        </label>
                        <div class="admin__field-control control">
                            <div class="admin__field">
                                <select name="sidebar" class="select admin__control-select" aria-required="true">
                                    <option value="">Select where to place the form</option>
                                    <?php $positions = ['content' => 'Content Top', 'page.bottom' => 'Content Bottom', 'footer-container' => 'Footer', 'sidebar.main' => 'Sidebar Top', 'div.sidebar.additional' => 'Sidebar Bottom'];
                                    foreach ($positions as $position => $name):?>
                                        <option
                                            value="<?php echo $position ?>"
                                            <?php if (isset($settings['sidebar']) && $position == $settings['sidebar']): ?>
                                                selected="selected"
                                            <?php endif ?>
                                        ><?php echo $name ?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
    </div>
</form>

<script>
    require(['jquery'],function($) {
        var sod = $('#publish'), forms = $('.forms'), webform_id = $('#webform_id'),
            webform_url = $('#webform_url');
        if (sod.prop('checked') === true) {
            forms.removeClass('hidden');
        }
        sod.change(function () {
            forms.toggleClass('hidden');
        });
        webform_url.val(webform_id.find(':selected').attr('data-url'));
        webform_id.change(function () {
            webform_url.val(webform_id.find(':selected').attr('data-url'));
        });
    });
</script>