<?php /** @var $block \GetResponse\GetResponseIntegration\Block\Webform */
$formsCollection = $block->getWebFormsCollection();
$webformSettings = $block->getWebformSettings();
?>
<style>
    .label {
        font-weight: bold;
    }

    .label label {
        display: inline-block;
    }

    td.label {
        vertical-align: top;
    }

    .value input {
        margin-top: 4px;
        width: 100%;
    }

    .note {
        color: #303030;
        font-size: 12px;
        margin-top: 5px;
    }

    .admin__scope-old input[type="checkbox"] {
        -moz-appearance: checkbox;
    }

    tr {
        margin-bottom: 5px;
    }

    .page-main-hint {
        float: left;
    }

    .page-main-hint span {
        display: inline-block;
        margin-top: 1rem;
    }

    .hidden {
        display: none
    }

</style>

<form method="post" action="<?php echo $block->getUrl('getresponseintegration/settings/webformpost'); ?>">
    <?php echo $block->getBlockHtml('formkey'); ?>

    <div class="page-main-actions">
        <div class="page-main-hint">
            <span>Add forms (or exit popups) to your store. Get new contacts when your customers fill them out.</span>
        </div>
        <div class="page-actions">
            <div class="page-actions-inner">
                <div class="page-actions-buttons">
                    <button id="export" title="Export" type="submit" class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button" aria-disabled="false">
                        <span class="ui-button-text">
                            <span>Save</span>
                        </span>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div id="page:main-container" class="page-columns">
        <div class="admin__old">
            <div id="container" class="main-col">
                <fieldset class="fieldset admin__fieldset no-display" id="publish_fieldset" style="display: block;">
                    <div class="admin__field field field-basic_publish required _required">
                        <label class="label admin__field-label" for="publish"></label>
                        <div class="admin__field-control control">
                            <div class="admin__field admin__field-option publish__field">
                                <input id="publish" name="publish" class="admin__control-checkbox" type="checkbox" value="1"
                                    <?php if ($webformSettings->isEnabled()):?>
                                        checked="checked"
                                    <?php endif ?>
                                >
                                <label class="admin__field-label" for="publish">Add contacts to GetResponse via forms (or exit popups)</label>
                            </div>
                        </div>
                    </div>
                    <div class="admin__field field field-basic_webform required _required forms <?php if (!$webformSettings->isEnabled()):?>hidden<?php endif ?>">
                        <label class="label admin__field-label" for="webform_id">
                            <span>Form</span>
                        </label>
                        <div class="admin__field-control control">
                            <div class="admin__field">
                                <select name="webform_id" id="webform_id" class="select admin__control-select" aria-required="true">
                                    <option value="">Select a form you want to display</option>
                                    <?php if (!empty($formsCollection->getWebforms())):?>
                                        <?php foreach ($formsCollection->getWebforms() as $form): ?>
                                            <option
                                                value="<?php echo $form->getId()?>"
                                                data-url="<?php echo $form->getUrl()?>"
                                                <?php if($webformSettings->getWebformId() == $form->getId()):?>
                                                    selected="selected"
                                                <?php endif ?>
                                            ><?php echo $form->getName() ?></option>
                                        <?php endforeach ?>
                                    <?php else: ?>
                                        <option value="" disabled="disabled">No forms</option>
                                    <?php endif ?>
                                </select>
                                <input type="hidden" value="" name="webform_url" id="webform_url" />
                            </div>
                        </div>
                    </div>
                    <div class="admin__field field field-basic_sidebar required _required forms <?php if (!$webformSettings->isEnabled()):?>hidden<?php endif ?>">
                        <label class="label admin__field-label" for="sidebar">
                            <span>Block position</span>
                        </label>
                        <div class="admin__field-control control">
                            <div class="admin__field">
                                <select name="sidebar" class="select admin__control-select" aria-required="true">
                                    <option value="">Select where to place the form</option>
                                    <?php $positions = ['content' => 'Content Top', 'page.bottom' => 'Content Bottom', 'footer-container' => 'Footer', 'sidebar.main' => 'Sidebar Top', 'div.sidebar.additional' => 'Sidebar Bottom'];
                                    foreach ($positions as $position => $name):?>
                                        <option
                                            value="<?php echo $position ?>"
                                            <?php if ($webformSettings->getSidebar() === $position): ?>
                                                selected="selected"
                                            <?php endif ?>
                                        ><?php echo $name ?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
    </div>
</form>

<script>
    require(['jquery'],function($) {
        var sod = $('#publish'), forms = $('.forms'), webform_id = $('#webform_id'),
            webform_url = $('#webform_url');
        if (sod.prop('checked') === true) {
            forms.removeClass('hidden');
        }
        sod.change(function () {
            forms.toggleClass('hidden');
        });
        webform_url.val(webform_id.find(':selected').attr('data-url'));
        webform_id.change(function () {
            webform_url.val(webform_id.find(':selected').attr('data-url'));
        });
    });
</script>