<form class="getresponse getresponse-create-list" method="post" id="getresponseaddrule"
      action="<?php echo Mage::helper("adminhtml")->getUrl('getresponse/contactlistrules/save'); ?>">

    <div class="content-header">
        <h3>New Rule</h3>
        <p class="form-buttons">
            <button title="Back" type="button" class="scalable back" onclick="setLocation('<?=Mage::helper("adminhtml")->getUrl('getresponse/contactlistrules/index');?>')" style=""><span><span><span>Back</span></span></span></button>
            <button type="submit" onclick="getresponseaddrule.submit();" name="Submit" id="saveContactList" class="scalable save"><span><span><span>Save Rule</span></span></span></button>
        </p>
    </div>

    <div class="entry-edit">
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>

                    <tr class="empty-space details">
                        <td colspan="2"></td>
                    </tr>

                    <tr>
                        <td class="label">If  customer buys in the category<span class="required">*</span></td>
                        <td class="value">
                            <?php if ( !empty($categories_tree)): ?>
                                <select class="GR_input" name="category_id" id="category_id">
                                    <?php echo $categories_tree; ?>
                                </select>
                            <?php else: ?>
                                <span class="error">An error occurred while trying to get categories.</span>
                                <?php endif ?>
                        </td>
                    </tr>

                    <tr class="empty-space details">
                        <td colspan="2"></td>
                    </tr>

                    <tr>
                        <td class="label">They are<span class="required">*</span></td>
                        <td class="value">
                            <?php if ( !empty($actions)): ?>
                                <select class="GR_input" name="action" id="action">
                                    <?php foreach ($actions as $id => $name): ?>
                                        echo '<option value="<?php echo $id ?>"><?php echo $name ?></option>
                                    <?php endforeach; ?>
                                </select>
                            <?php else: ?>
                                <span class="error">An error occurred while trying to get action.</span>
                            <?php endif ?>
                        </td>
                    </tr>

                    <tr class="empty-space details">
                        <td colspan="2"></td>
                    </tr>

                    <tr>
                        <td class="label">Into the contact list<span class="required">*</span></td>
                        <td class="value">
                            <?php if ( !empty($campaigns)): ?>
                                <select class="GR_input" name="campaign_id" id="campaign_id">
                                    <?php foreach ($campaigns as $id => $name): ?>
                                        <option value="<?php echo $id ?>"><?php echo $name ?></option>
                                    <?php endforeach ?>
                                </select>
                            <?php else: ?>
                                <span class="error">An error occurred while trying to get campaigns.</span>
                                <?php endif ?>
                        </td>
                    </tr>

                    <tr class="empty-space details">
                        <td colspan="2"></td>
                    </tr>

                    <?=$autoresponder_block?>

                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>"/>
</form>