<form class="getresponse getresponse-create-list" method="post" id="getresponseaddrule"
      action="<?php echo Mage::helper("adminhtml")->getUrl('getresponse/index/create_contact_list_rule'); ?>">

    <div class="content-header">
        <h3>New Rule</h3>
        <p class="form-buttons">
            <button title="Back" type="button" class="scalable back" onclick="setLocation('<?=Mage::helper("adminhtml")->getUrl('getresponse/index/automation');?>')" style=""><span><span><span>Back</span></span></span></button>
            <button type="submit" onclick="getresponseaddrule.submit();" name="Submit" id="saveContactList" class="scalable save"><span><span><span>Save Rule</span></span></span></button>
        </p>
    </div>

    <div class="entry-edit">
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>

                    <tr class="empty-space details">
                        <td colspan="2"></td>
                    </tr>

                    <tr>
                        <td class="label">If  customer buys in the category<span class="required">*</span></td>
                        <td class="value">
                            <?php if ( !empty($settings->categories_tree)): ?>
                                <select class="GR_input" name="category_id" id="category_id">
                                    <?php echo $settings->categories_tree; ?>
                                </select>
                            <?php else: ?>
                                <span class="error">An error occurred while trying to get categories.</span>
                                <?php endif ?>
                        </td>
                    </tr>

                    <tr class="empty-space details">
                        <td colspan="2"></td>
                    </tr>

                    <tr>
                        <td class="label">They are<span class="required">*</span></td>
                        <td class="value">
                            <?php if ( !empty($settings->actions)): ?>
                                <select class="GR_input" name="action" id="action">
                                    <?php foreach ($settings->actions as $id => $name): ?>
                                        echo '<option value="<?php echo $id ?>"><?php echo $name ?></option>
                                    <?php endforeach; ?>
                                </select>
                            <?php else: ?>
                                <span class="error">An error occurred while trying to get action.</span>
                            <?php endif ?>
                        </td>
                    </tr>

                    <tr class="empty-space details">
                        <td colspan="2"></td>
                    </tr>

                    <tr>
                        <td class="label">Into the contact list<span class="required">*</span></td>
                        <td class="value">
                            <?php if ( !empty($settings->campaigns)): ?>
                                <select class="GR_input" name="campaign_id" id="campaign_id">
                                    <?php foreach ($settings->campaigns as $id => $name): ?>
                                        <option value="<?php echo $id ?>"><?php echo $name ?></option>
                                    <?php endforeach ?>
                                </select>
                            <?php else: ?>
                                <span class="error">An error occurred while trying to get campaigns.</span>
                                <?php endif ?>
                        </td>
                    </tr>

                    <tr class="empty-space details">
                        <td colspan="2"></td>
                    </tr>

                    <tr>
                        <td class="label"></td>
                        <td class="value">
                            <input type="checkbox" disabled name="gr_autoresponder" id="gr_autoresponder" value="1" />
                            <label for="gr_autoresponder" class="inactive">Add to autoresponder cycle</label>
                        </td>
                    </tr>

                    <tr>
                        <td class="label"><label for="autoresponder">Autoresponder day</label></td>
                        <td class="value">
                            <select id="cycle_day" class="inactive" name="cycle_day">
                                <option value="">no autresponders</option>
                            </select>
                        </td>
                    </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script>

        available_cycles = jQuery.parseJSON('<?php echo isset($settings->campaign_days) ? addslashes(json_encode($settings->campaign_days)) : "{}"; ?>');

        cycles.init(
            available_cycles,
            jQuery('#campaign_id'),
            jQuery('#cycle_day'),
            jQuery('#gr_autoresponder'),
            jQuery('label[for="gr_autoresponder"]'),
            <?php echo isset($settings->api['cycle_day']) ? $settings->api['cycle_day'] : ''; ?>
        );

    </script>

    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>"/>
</form>