<form class="getresponse getresponse-account" method="post"
      action="<?php echo Mage::helper("adminhtml")->getUrl('getresponse/index/apikey'); ?>">
    <div>
        <div class="content-header">
            <h3>GetResponse Account</h3>
            <p class="form-buttons">
                <button type="submit" name="Submit"><span>Connect</span></button>
            </p>
        </div>

        <div class="entry-edit">

            <input name="form_key" type="hidden"
                   value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>

            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend">Use API key to Connect Your Site to GetResponse</h4>
            </div>
            <div class="fieldset">
                <div class="hor-scroll">
                    <table cellspacing="0" class="form-list">
                        <tbody>
                        <tr>
                            <td class="label"><label for="api_key">API key</label></td>
                            <td class="value">
                                <input
                                        class="input-text"
                                        type="text"
                                        id="api_key"
                                        name="api_key"
                                        value="<?php if (isset($settings->api['api_key'])) : echo $settings->api['api_key']; endif ?>"/>

                                <p class="note" id="note_identifier"><span>Your API key is part of the settings of your GetResponse account.<br /> Log in to GetResponse and go to <strong>My profile > Integration & API > API</strong> to find the key.</span></p>
                            </td>
                        </tr>
                        <tr>
                            <td class="label"></td>
                            <td class="value enterprise_account">
                                <input
                                        type="checkbox"
                                        name="getresponse_360_account"
                                        id="getresponse_360_account"
                                    <?php if (!empty($settings->api['api_domain'])) : ?> checked="checked" <?php endif ?>
                                        value="1">
                                <label class="GR_label_checkbox" for="getresponse_360_account">I have the Enterprise
                                    package</label>
                            </td>
                        </tr>

                        <tr class="getresponse_360_account_options" <?php if (empty($settings->api['api_domain'])) : ?> style="display: none" <?php endif ?>>
                            <td class="label"><label for="api_key">Account type</label></td>
                            <td class="value">
                                <select class="" name="api_url" id="api_url">
                                    <option
                                            value="<?php echo $settings->main['api_url_360_pl']; ?>" <?php if (isset($settings->api['api_url']) && $settings->api['api_url'] == $settings->main['api_url_360_pl']) : ?> selected="selected" <?php endif ?>>
                                        GetResponse360 PL
                                    </option>
                                    <option
                                            value="<?php echo $settings->main['api_url_360_com']; ?>" <?php if (isset($settings->api['api_url']) && $settings->api['api_url'] == $settings->main['api_url_360_com']) : ?> selected="selected" <?php endif ?>>
                                        GetResponse360 COM
                                    </option>
                                </select>
                            </td>
                        </tr>

                        <tr class="getresponse_360_account_options" <?php if (empty($settings->api['api_domain'])) : ?> style="display: none" <?php endif ?>>
                            <td class="label"><label for="api_key">Your domain</label></td>
                            <td class="value">
                                <input
                                        class="input-text"
                                        type="text"
                                        name="api_domain"
                                        value="<?php if (isset($settings->api['api_domain'])) : echo $settings->api['api_domain']; endif ?>"/>

                                <p class="note no-image"><span>Enter your domain without protocol (https://) eg: "example.com"</span>
                                </p>

                            </td>
                        </tr>


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <script>
            jQuery('#getresponse_360_account').change(function () {
                var value = jQuery('#getresponse_360_account:checked').val();
                if (value === '1') {
                    jQuery('.getresponse_360_account_options').show();
                }
                else {
                    jQuery('.getresponse_360_account_options').hide();
                }
            });
        </script>
    </div>
</form>