<form class="getresponse getresponse-contact-list-rules" method="post" action="#">

    <div id="messages">
        <ul class="messages">
            <li class="notice-msg">
                <ul>
                    <li><span>
                        <?php if (0 === count($rules)): ?>
                            Define rules that move or copy contacts between GetResponse lists when people make purchases in the selected product category.
                        <?php else: ?>
                            Automatically move or copy your customers between your GetResponse contact list when people purchase in Magento product category.
                        <?php endif ?>
                    </span></li>
                </ul>
            </li>
        </ul>
    </div>

    <div class="content-header">
        <h3>Contact List Rules</h3>
        <p class="form-buttons">
            <button onclick="setLocation('<?php echo Mage::helper("adminhtml")->getUrl("getresponse/contactlistrules/add"); ?>')" type="button" class="scalable add" name="Submit"><span><span><span>Add New Rule</span></span></span></button>
        </p>
    </div>

    <div class="fieldset fieldset-wide fieldset-wide-no-padding">
        <div class="grid">
            <div class="hor-scroll">

                <p>Total <?php echo count($rules) ?> records found</p>

                <table cellspacing="0" class="data customs-table">
                    <colgroup>
                        <col width="500">
                        <col width="400">
                        <col width="150">
                        <col width="150">
                        <col width="400">
                        <col width="100">
                    </colgroup>
                    <thead>
                    <tr class="headings">
                        <th class="no-link"><span class="nobr">If customer buys in the category</span></th>
                        <th class="no-link"><span class="nobr">They are</span></th>
                        <th class="no-link"><span class="nobr">Into the contact list</span></th>
                        <th class="no-link"><span class="nobr">Add into the cycle on day</span></th>
                        <th class="no-link"><span class="nobr">Autoresponder</span></th>
                        <th class="no-link last" style="text-align: center"><span class="nobr">Action</span></th>
                    </tr>
                    </thead>

                    <tbody>
                        <?php $even = true; ?>
                        <?php if ( !empty($rules)): ?>

                            <?php foreach ($rules as $automation): ?>

                                <tr <?php if ($even): ?> class="even"<?php endif ?>>
                                <td>
                                    <?php if (isset($categories[$automation['category_id']])) : echo $categories[$automation['category_id']]['name']; endif ?>
                                </td>
                                <td>
                                    <?php
                                    echo $automation['action']; ?>
                                </td>
                                <td>
                                    <?php if (isset($campaigns[$automation['campaign_id']])) : echo $campaigns[$automation['campaign_id']]; endif ?>
                                </td>
                                <td style="text-align: center;">
                                    <input
                                        data-automation="<?php echo $automation['id']; ?>"
                                        class="gr-active"
                                        type="checkbox"
                                        onclick="return false;"
                                        value="1"
                                        <?php if ($automation['cycle_day'] == 1) : echo "checked"; endif ?>
                                    >
                                </td>
                                <td>
                                    <?php if (isset($campaign_days[$automation['campaign_id']]) && 1 == $automation['active']): ?>
                                        <?php foreach ($campaign_days[$automation['campaign_id']] as $campaign): ?>
                                            <?php if ($campaign['day'] == $automation['cycle_day']): ?>
                                            <?php echo "(Day: " . $campaign['day'] . ") " .  $campaign['name'] ?>
                                                <?php endif ?>
                                        <?php endforeach ?>
                                    <?php endif ?>
                                </td>
                                <td style="text-align: center">
                                    <a href="<?php echo Mage::helper("adminhtml")->getUrl("getresponse/contactlistrules/edit/id/" . $automation['id']); ?>">Edit</a>

                                </td>
                                </tr>

                                <?php $even = !$even ?>
                            <?php endforeach; ?>
                        <?php else: ?>
                        <tr>
                            <td colspan="6">
                                <p class="not-found">No records found.</p>
                            </td>
                        </tr>
                        <?php endif ?>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</form>