<form class="getresponse getresponse-create-list" method="post" id="getresponselist"
      action="<?php echo Mage::helper("adminhtml")->getUrl('getresponse/index/create_new_list'); ?>">

    <input type="hidden" name="back_url" value="<?php echo $back_url; ?>" />

    <div class="content-header">
        <h3>New List</h3>
        <p class="form-buttons">

            <button title="Back" type="button" class="scalable back" onclick="window.history.back()" style=""><span><span><span>Back</span></span></span></button>

            <button type="submit" onclick="getresponselist.submit();" name="Submit" id="saveContactList" class="scalable save"><span>Save New List</span></button>
        </p>
    </div>

    <div class="entry-edit">
        <div class="fieldset">
            <div style="width: 100%; overflow: hidden; padding-bottom: 4px; margin-bottom: -4px;">
                <table cellspacing="0" class="form-list">
                    <tbody>

                    <tr>
                            <td class="label">List name <span class="required">*</span></td>
                            <td class="value">
                                <input type="text" class="input-text" name="campaign_name" id="form_campaign_name" />
                            </td>
                        </tr>

                        <tr class="empty-space details">
                            <td colspan="2"></td>
                        </tr>

                        <tr>
                            <td class="label">From field <span class="required">*</span></td>
                            <td class="value">
                                <?php if ( !empty($settings->from)): ?>
                                <select name="from" id="form_from">
                                    <option value="">Select from field</option>
                                    <?php foreach ($settings->from as $from): ?>
                                        <?php if ($from->isActive == true): ?>
                                            <option
                                                value="<?php echo $from->fromFieldId ?>">
                                                <?php echo $from->name . ' (' . $from->email . ')' ?></option>
                                        <?php endif ?>
                                    <?php endforeach ?>
                                </select>
                                <?php else: ?>
                                    <span class="error">An error occurred while trying to get from fields.</span>
                                <?php endif ?>
                            </td>
                        </tr>

                        <tr class="empty-space details">
                            <td colspan="2"></td>
                        </tr>

                        <tr>
                            <td class="label">Reply-to <span class="required">*</span></td>
                            <td class="value">
                                <?php if ( !empty($settings->from)): ?>
                                <select name="reply_to" id="form_reply_to">
                                    <option value="">Select reply-to-address</option>
                                    <?php foreach ($settings->from as $from): ?>
                                        <?php if ($from->isActive == true):?>
                                            <option
                                                value="<?php echo $from->fromFieldId?>">
                                                <?php echo $from->name . ' (' . $from->email . ')'?></option>
                                        <?php endif ?>
                                    <?php endforeach ?>
                                </select>
                                <?php else: ?>
                                    <span class="error">An error occurred while trying to get reply to fields.</span>
                                <?php endif ?>
                            </td>
                        </tr>

                        <tr class="empty-space details">
                            <td colspan="2"></td>
                        </tr>

                        <tr>
                            <td class="label">Confirmation subject <span class="required">*</span></td>
                            <td class="value">
                                <?php if ( !empty($settings->confirmation_subject)): ?>
                                <select name="confirmation_subject" id="form_confirmation_subject">
                                    <option value="">Select confirmation message subject</option>
                                    <?php foreach ($settings->confirmation_subject as $cs): ?>
                                        <option value="<?php echo $cs->subscriptionConfirmationSubjectId ?>"><?php echo $cs->subject ?></option>
                                    <?php endforeach ?>
                                </select>
                                <?php else: ?>
                                    <span class="error">An error occurred while trying to Confirmation subject fields.</span>
                                <?php endif ?>
                            </td>
                        </tr>

                        <tr class="empty-space details">
                            <td colspan="2"></td>
                        </tr>

                        <tr>
                            <td class="label">Confirmation body <span class="required">*</span></td>
                            <td class="value">
                                <?php if ( !empty($settings->confirmation_body)): ?>
                                <select name="confirmation_body" id="form_confirmation_body">
                                    <option value="">Select confirmation message body template</option>
                                    <?php foreach ($settings->confirmation_body as $cb): ?>
                                        <option value="<?php echo $cb->subscriptionConfirmationBodyId ?>"><?php echo $cb->contentPlain?></option>
                                    <?php endforeach ?>
                                </select>
                                <?php else: ?>
                                    <span class="error">An error occurred while trying to get Confirmation body fields.</span>
                                <?php endif ?>
                            </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td class="value">
                                <p class="note no-image">
                                The confirmation message body and subject depend on System >> Configuration >> General >> Locale Options.<br />
                                By default all lists you create in Magento have double opt-in enabled. You can change this later in your <span class="link">list settings</span>.</p>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script>
        var errors_messages = {
            form_campaign_name: 'You need to enter a name that\'s at least 3 characters long',
            form_from: 'You need to select a sender email address',
            form_reply_to: 'This is a required field',
            form_confirmation_subject: 'You need to select a subject line for the subscription confirmation message',
            form_confirmation_body: 'You need to select confirmation message body template'
        };
        var fields = ['form_campaign_name', 'form_from', 'form_reply_to', 'form_confirmation_subject', 'form_confirmation_body'];

        jQuery('#saveContactList').on('click', function() {

            var formValid = true;

            jQuery('div.validation-advice').each(function() {
                jQuery(this).remove();
            });

            fields.forEach(function(el) {
                var element = jQuery('#' + el);

                if (jQuery(element).is('input')) {

                    if (jQuery(element).val().length < 3) {

                        formValid = false;
                        element.after(function() {
                            return jQuery("<div/>").addClass('validation-advice').text(errors_messages[el]);
                        })
                    }

                } else if (jQuery(element).is('select')) {

                    if (jQuery(element).val().length === 0) {

                        formValid = false;
                        element.after(function() {
                            return jQuery("<div/>").addClass('validation-advice').text(errors_messages[el]);
                        })
                    }
                }
            });

            if (!formValid) {
                return false;
            }
        });
    </script>

    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>"/>


</form>