<?php

declare(strict_types=1);

use GetResponse\GetResponseIntegration\Block\Admin\Account;

/** @var Account $block */
$isApiActive = $block->isConnectedToGetResponse();

if ($isApiActive) {
    $account = $block->getAccountInfo();
}
?>

<form method="post" action="<?php echo $block->getUrlWithScope('getresponse/account/save'); ?>">
    <?php echo $block->getBlockHtml('formkey'); ?>
    <div class="page-main-actions">
        <?php require('switch_scope.phtml') ?>
        <div class="page-main-hint">
            <span>Use API key to connect your site and GetResponse.</span>
        </div>
        <div class="page-actions">
            <div class="page-actions-inner">
                <div class="page-actions-buttons">
                    <?php if (!$isApiActive) : ?>
                        <button id="saveBtn" title="Connect" type="submit" class="action-default scalable connect primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button" aria-disabled="false">
                            <span class="ui-button-text">
                                <span>Connect</span>
                            </span>
                        </button>
                        <?php else : ?>
                        <button id="disconnectBtn" title="disconnect" class="action-default scalable disconnect primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button" aria-disabled="false">
                            <span class="ui-button-text">
                                <span>Disconnect</span>
                            </span>
                        </button>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    <div id="page:main-container" class="page-columns">
        <div class="admin__old">
            <div id="container" class="main-col">
                <?php if (!$isApiActive) : ?>
                    <fieldset class="fieldset admin__fieldset no-display" id="apiKey_fieldset" style="display: block;">
                        <div class="admin__field field field-basic_apiKey required _required with-note">
                            <label class="label admin__field-label" for="apiKey">
                                <span>API key</span>
                            </label>
                            <div class="admin__field-control control">
                                <input id="apiKey" name="apiKey" value="<?php echo $block->getLastPostedApiKey(); ?>" title="API Key" class="basic_behavior input-text input-text admin__control-text required-entry _required" type="text" aria-required="true">
                                <div class="note admin__field-note" id="basic_behavior_allowed_error_count-note">
                                    Your API key is part of the settings of your GetResponse account. Log in to GetResponse and go to <a href="https://app.getresponse.com/manage_api.html" target="_blank">My account > API & OAuth</a> to find the key.
                                </div>
                                <div class="admin__field admin__field-option is_mx__field">
                                    <input id="is_mx" name="is_mx" class="admin__control-checkbox" type="checkbox" value="1" <?php if ($block->getLastPostedTypeOfAccountCheckboxValue()) { ?>checked="checked"<?php } ?>>
                                    <label class="admin__field-label" for="is_mx"><span>I have the Enterprise package</span></label>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                    <fieldset id="is_mx_options" class="fieldset admin__fieldset is_mx_options <?php if (1 !== $block->getLastPostedTypeOfAccountCheckboxValue()) { ?>hidden<?php } ?>">
                        <div class="admin__field field field-basic_is_mx">
                            <label class="label admin__field-label" for="api_url">
                                <span>Account type</span>
                            </label>
                            <div class="admin__field-control control">
                                <div class="admin__field">
                                    <select id="url" name="url" title="Account Type" class="select admin__control-select" aria-required="true">
                                        <option value="https://api3.getresponse360.com/v3/" <?php if('https://api3.getresponse360.com/v3/' === $block->getLastPostedApiUrl()) { ?> selected="selected"<?php } ?>>GetResponse Enterprise COM</option>
                                        <option value="https://api3.getresponse360.pl/v3/" <?php if('https://api3.getresponse360.pl/v3/' === $block->getLastPostedApiUrl()) { ?> selected="selected"<?php } ?>>GetResponse Enterprise PL</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="admin__field field field-basic_getresponse_api_domain required _required with-note">
                            <label class="label admin__field-label" for="domain">
                                Your domain
                            </label>
                            <div class="admin__field-control control">
                                <div class="admin__field">
                                    <input type="text" name="domain" id="domain"
                                           value="<?php echo $block->getLastPostedApiDomain();?>"
                                           class="input-text admin__control-text">
                                </div>
                                <div class="note admin__field-note">
                                    Enter your domain without protocol (https://) eg: "example.com"
                                </div>
                            </div>
                        </div>
                    </fieldset>

                    <?php else : ?>
                    <legend class="admin__legend legend title">
                        <span>GetResponse account data</span>
                    </legend>
                    <table class="account_data">
                        <tr>
                            <td>
                                <label for="getresponse_getresponse_general_apiKey">Status:</label>
                            </td>
                            <td>
                                <div><span class="status-connected">CONNECTED</span></div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                API Key:
                            </td>
                            <td>
                                <span name="apiKey" id="apiKey"><?php echo $block->getHiddenApiKey(); ?></span>
                            </td>
                        </tr>
                        <?php endif; ?>
                            <?php
                            if ($isApiActive) : ?>
                        <tr>
                            <td>Name:</td>
                            <td><?php echo $account->getFirstName() . ' ' . $account->getLastName(); ?></td>
                        </tr>
                        <tr>
                            <td>Email:</td>
                            <td><?php echo $account->getEmail(); ?></td>
                        </tr>
                        <?php if (!empty($account->getCompanyName())) : ?>
                            <tr>
                                <td>Company:</td>
                                <td><?php echo $account->getCompanyName(); ?></td>
                            </tr>
                        <?php endif; ?>
                        <tr>
                            <td>Phone:</td>
                            <td><?php echo $account->getPhone(); ?></td>
                        </tr>
                        <tr>
                            <td>Address:</td>
                            <td><?php echo $account->getStreet() . ' ' . $account->getZipCode() . ' ' . $account->getCity() . ' ' . $account->getState() . ' ' . $account->getCountryCode(); ?></td>
                        </tr>
                    </table>
                <?php
                endif;
                ?>
            </div>
        </div>
    </div>
</form>

<div id="popup-modal" style="display: none;">
    <div>When you disconnect, you won’t be able to add new contacts, track site visits, or send ecommerce data to GetResponse.</div>
</div>

<input type="hidden" id="jsDeleteUrl" value="<?php echo $block->getUrlWithScope("getresponse/account/delete"); ?>" />

<script>

    require(['settings']);
    
</script>