<?php /** @var $block \GetResponse\GetResponseIntegration\Block\Rules */
$autoResponders = $block->getAutoresponders();
$rules = $block->getRulesCollection()->getRules();
?>

<div class="page-main-actions">
    <div class="page-main-hint">
        <span>Automatically move or copy your customers between your GetResponse contact lists when people purchase in Magento product category.</span>
    </div>
    <div class="page-actions">
        <div class="page-actions-inner">
            <div class="page-actions-buttons">
                <button id="getresponse_create_new_rule" onclick="location.href='<?php echo $block->getUrl('getresponse/rules/create'); ?>'" title="Add New Rule" class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" type="button" role="button" aria-disabled="false">
                    <span class="ui-button-text">
                        <span>Add New Rule</span>
                    </span>
                </button>
            </div>
        </div>
    </div>
</div>
<div id="page:main-container" class="page-columns">
    <div class="admin__old">
        <div id="container" class="main-col">
            <div id="automation-table-wrap" class="admin__data-grid-wrap" data-role="grid-wrapper">
                <table class="data-grid" id="automation-table">
                    <thead>
                        <tr>
                            <th class="data-grid-th">
                                <span class="data-grid-cell-content">If customer buys in the category</span>
                            </th>

                            <th class="data-grid-th">
                                <span class="data-grid-cell-content">they are</span>
                            </th>

                            <th class="data-grid-th">
                                <span class="data-grid-cell-content">into the contact list</span>
                            </th>

                            <th class="data-grid-th">
                                <span class="data-grid-cell-content">Add to autoresponder cycle</span>
                            </th>
                            <th class="data-grid-th">
                                <span class="data-grid-cell-content">Autoresponder</span>
                            </th>

                            <th class="data-grid-th">
                                <span class="data-grid-cell-content">Action</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php if (empty($rules)): ?>
                        <tr>
                            <td colspan="6" class="no-data">
                                We couldn't find any records
                            </td>
                        </tr>
                        <?php else: ?>
                        <?php foreach ($rules as $rule): ?>
                            <tr class="data-row" data-role="data-grid-bulk-row">

                                <td class="category">
                                    <?php echo $block->getCategoryName($rule->getCategory()); ?>
                                </td>

                                <td class="action">
                                    <?php echo $block->getAction($rule->getAction()); ?>
                                </td>

                                <td class="campaign">
                                    <?php $campaign = $block->getListById($rule->getCampaign()); ?>
                                    <?php echo isset($campaign['name']) ? $campaign['name'] : ''; ?>
                                </td>

                                <td>
                                    <input type="checkbox" disabled="disabled"
                                           <?php echo !empty($rule->getAutoresponderDay()) ? 'checked="checked"' : '' ?> />
                                </td>

                                <td class="cycle_day_edit">
                                    <?php if (!empty($rule->getAutoresponderDay())):?>

                                    (Day: <?php echo $rule->getAutoresponderDay() ?>)
                                    <?php  echo isset($autoResponders[$rule->getCampaign()][$rule->getAutoresponderId()]) ? $autoResponders[$rule->getCampaign()][$rule->getAutoresponderId()]['name'] : '' ?>
                            <?php endif ?>
                                </td>

                                <td>
                                    <a href="<?php echo $block->getUrl('getresponse/rules/edit/', array('id' => $rule->getId())); ?>">Edit</a>
                                </td>

                            </tr>
                        <?php endforeach ?>
                    <?php endif ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<input type="hidden" id="jsAutoresponders" value='<?php echo json_encode($autoResponders); ?>'/>