<?php

declare(strict_types=1);

use GetResponse\GetResponseIntegration\Block\Admin\Export;
use GetResponse\GetResponseIntegration\Block\Admin\Registration;
use GetResponse\GetResponseIntegration\Domain\GetResponse\CustomFieldsMapping\CustomFieldsMappingCollection;
use GetResponse\GetResponseIntegration\Domain\GetResponse\CustomFieldsMapping\MagentoCustomerAttribute\MagentoCustomerAttribute;
use GrShareCode\CustomField\CustomFieldCollection;

/** @var Registration|Export $block */
/** @var CustomFieldsMappingCollection $customFieldsMappingCollection */
/** @var CustomFieldCollection $customFieldsFromGetResponse */
/** @var array $magentoCustomerAttributes */
$customFieldsFromGetResponse = $block->getCustomFieldsFromGetResponse();
$customFieldsMappingCollection = $block->getCustomFieldsMapping();
$magentoCustomerAttributes = $block->getMagentoCustomerAttributes();
$magentoCustomerAttributesArray = $magentoCustomerAttributes->toArray();
?>
<div class="admin__data-grid-header admin__data-grid-toolbar">
    <button id="addNewMappingBtn" title="Add new mapping" type="button" class="action- scalable action-secondary">
        <span>Add new mapping</span>
    </button>
</div>
<div class="admin__data-grid-wrap admin__data-grid-wrap-static">
    <table class="data-grid" data-role="grid">
        <thead>
        <tr>
            <th class="data-grid-th _draggable">
                <span class="data-grid-cell-content">Customer details</span>
            </th>
            <th class="data-grid-th _draggable _ascend">
                <span class="data-grid-cell-content">Custom fields in GetResponse</span>
            </th>
            <th class="data-grid-th">
                <span class="data-grid-cell-content">Action</span>
            </th>
        </tr>
        </thead>
        <tbody id="customsDataBody">
        <?php foreach ($customFieldsMappingCollection as $key => $custom): ?>
            <?php if ($custom->isDefault()): ?>
                <tr class="data-row <?php if ($key % 2): ?>_odd-row<?php endif ?>">
                    <td>
                        <div class="data-grid-cell-content">
                            <select disabled name="custom[]">
                                <option selected="selected"
                                        value="<?php echo $custom->getMagentoAttributeType() . '_' . $custom->getMagentoAttributeCode() ?>">
                                    <?php echo $magentoCustomerAttributesArray[$custom->getMagentoAttributeType() . '_' . $custom->getMagentoAttributeCode()] ?>
                                </option>
                            </select>
                        </div>
                    </td>
                    <td>
                        <div class="data-grid-cell-content">
                            <select disabled name="custom[]">
                                <option selected="selected" value="">
                                    <?php echo $custom->getGetResponseDefaultLabel() ?>
                                </option>
                            </select>
                        </div>
                    </td>
                    <td>
                        <div class="data-grid-cell-content"></div>
                    </td>
                </tr>

            <?php else: ?>

                <tr class="data-row <?php if ($key % 2): ?>_odd-row<?php endif ?>">
                    <td>
                        <div class="data-grid-cell-content">
                            <select name="custom[]">
                                <option value="">Select a Customer Attribute</option>
                                <?php
                                /** @var MagentoCustomerAttribute $magentoCustomerAttribute */
                                foreach ($magentoCustomerAttributes as $magentoCustomerAttribute): ?>
                                    <option
                                        <?php if ($custom->getMagentoAttributeCode() === $magentoCustomerAttribute->getAttributeCode()
                                                && $custom->getMagentoAttributeType() === $magentoCustomerAttribute->getAttributeType()): ?>
                                            selected="selected"
                                        <?php endif ?>
                                            value="<?php echo $custom->getMagentoAttributeType() . '_' . $magentoCustomerAttribute->getAttributeCode() ?>">
                                        <?php echo $magentoCustomerAttribute->getFrontendLabel() ?>
                                    </option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </td>
                    <td>
                        <div class="data-grid-cell-content">
                            <select name="gr_custom[]" class="getResponseCustomFieldSelect">
                                <option value="">Select a Custom Field</option>
                                <?php
                                /** @var \GrShareCode\CustomField\CustomField $customFieldFromGetResponse */
                                foreach ($customFieldsFromGetResponse as $customFieldFromGetResponse): ?>
                                    <option
                                        <?php if ($custom->getGetResponseCustomId() === $customFieldFromGetResponse['id']): ?>
                                            selected="selected"
                                        <?php endif ?>
                                            value="<?php echo $customFieldFromGetResponse['id'] ?>">
                                        <?php echo $customFieldFromGetResponse['name'] ?>
                                    </option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </td>
                    <td>
                        <div class="data-grid-cell-content">
                            <a href="#" class="deleteCustomBtn">Delete</a>
                        </div>
                    </td>
                </tr>
            <?php endif ?>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
<input type="hidden" id="jsMagentoCustomerAttributes" value='<?php echo json_encode($magentoCustomerAttributesArray); ?>'/>
<input type="hidden" id="jsGetResponseCustomFields" value='<?php echo json_encode($customFieldsFromGetResponse); ?>'/>
<script>
    require(['customsGrid']);
</script>