<?php

declare(strict_types=1);

use GetResponse\GetResponseIntegration\Block\Admin\Export;
use GrShareCode\ContactList\ContactList;
use GrShareCode\ContactList\ContactListCollection;
use GrShareCode\Shop\Shop;
use GrShareCode\Shop\ShopsCollection;

/** @var Export $block */
/** @var ContactListCollection $lists */
$lists = $block->getLists();
/** @var ShopsCollection $shops */
$shops = $block->getShops();
?>

<form method="post" action="<?php echo $block->getUrlWithScope('getresponse/export/process'); ?>" style="margin-top: 20px;">
    <?php echo $block->getBlockHtml('formkey'); ?>

    <div class="page-main-actions">
        <?php require('switch_scope.phtml') ?>
        <div class="page-main-hint">
            <span>Export your customer information from Magento to your GetResponse account.</span>
        </div>
        <div class="page-actions">
            <div class="page-actions-inner">
                <div class="page-actions-buttons">
                    <button id="getresponse_add_new_campaign" title="Create Contact List" type="button" onclick="location.href='<?php echo $block->getUrlWithScope('getresponse/lists/index/back/export'); ?>'" class="action-scalable action-secondary"  >
                        <span>Create Contact List</span>
                    </button>
                    <button id="export" title="Export" type="submit" class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button" aria-disabled="false">
                        <span class="ui-button-text">
                            <span>Export</span>
                        </span>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div id="page:main-container" class="page-columns">
        <div class="admin__old">
            <div id="container" class="main-col">
                <div id="messages">
                    <div class="messages">
                        <div class="message message-notice notice">
                            <div data-ui-id="messages-message-notice">
                                Use this option for one time export of your existing customers
                            </div>
                        </div>
                    </div>
                </div>

                <fieldset class="fieldset admin__fieldset" id="gr_enabled_fieldset" style="display: block;">

                    <div class="admin__field field field-basic_campaign required _required forms">
                        <label class="label admin__field-label" for="campaign_id">
                            <span>Contact list</span>
                        </label>
                        <div class="admin__field-control control">
                            <div class="admin__field">
                                <select name="campaign_id" id="campaign_id" class="select admin__control-select" aria-required="true">
                                    <option value="">Select a list</option>
                                        <?php /** @var ContactList $list */
                                        foreach ($lists as $list): ?>
                                            <option value="<?php echo $list->getId()?>"><?php echo $list->getName()?></option>
                                        <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="admin__field field field-basic_autoresponder forms">
                        <label class="label admin__field-label" for="gr_enabled"></label>
                        <div class="admin__field-control control">
                            <div class="admin__field admin__field-option gr_enabled__field">
                                <input class="admin__control-checkbox"
                                       type="checkbox"
                                       name="gr_autoresponder"
                                       id="gr_autoresponder"
                                       value="1"
                                />
                                <label class="admin__field-label" for="gr_autoresponder">Add to autoresponder cycle</label>
                            </div>
                        </div>
                    </div>

                    <div class="admin__field field field-basic_autoresponder forms hidden" id="field-autoresponder">
                        <label class="label admin__field-label" for="cycle_day">
                            <span>Autoresponder day</span>
                        </label>
                        <div class="admin__field-control control">
                            <div class="admin__field cycle_day">
                                <select name="cycle_day" id="cycle_day" class="select admin__control-select" aria-required="true" disabled="disabled"></select>
                            </div>
                        </div>
                    </div>

                    <div class="admin__field field" id="field-ecommerce">

                        <label class="label admin__field-label">
                            <span>Ecommerce data</span>
                        </label>
                        <div class="admin__field-control control">
                            <div class="admin__field admin__field-option gr_enabled__field">
                                <input class="admin__control-checkbox"
                                       type="checkbox"
                                       name="ecommerce"
                                       id="ecommerce"
                                       value="1"
                                />
                                <label class="admin__field-label" for="ecommerce">Include ecommerce data in this export</label>
                            </div>
                        </div>
                    </div>

                    <div class="admin__field field field-basic_store hidden" id="store-box">
                        <label class="label admin__field-label" for="store_id">
                            <span>Store</span>
                        </label>
                        <div class="admin__field-control control">
                            <div class="admin__field">
                                <select name="store_id" id="store_id" class="select admin__control-select" aria-required="true">
                                    <option value="">Select a store</option>
                                        <?php /** @var Shop $shop */
                                        foreach ($shops as $shop): ?>
                                            <option value="<?php echo $shop->getId()?>"><?php echo $shop->getName() ?></option>
                                        <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="admin__field field field-basic_subscription with-note forms">
                        <label class="label admin__field-label" for="subscription">Contacts info</label>
                        <div class="admin__field-control control">
                            <div class="admin__field admin__field-option gr_enabled__field">
                                <input class="admin__control-checkbox"
                                        type="checkbox"
                                        name="gr_sync_order_data"
                                        id="gr_sync_order_data"
                                        value="1"
                                >
                                <label class="admin__field-label" for="gr_sync_order_data">Update contact info</label>
                                <div class="note admin__field-note" id="gr_sync_order_data-note">
                                    Select this option if you want to overwrite contact details that already exist in your GetResponse database.<br/>Clear this option to keep existing data.
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>
                <div id="customNameFieldsRow" class="forms config admin__scope-old hidden">
                    <div id="customNameFields">
                        <?php include 'customs_grid.phtml'; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<input type="hidden" id="jsAutoresponders" value='<?php echo $block->getSerializedAutoresponders() ?>'/>
<script>
    require(['exportContacts']);
</script>