
<div id="container" class="main-col">

    <div>
        You can now manage the Magento integration directly in your GetResponse account. To view and edit the integration, <a href="https://app.getresponse.com/integrations/magentohybrid" target="_blank">go to the integration setup page in GetResponse</a>. <br/>
        Link do faq: <a href="#" target="_blank">Learn more about the updated integration</a>.
    </div>
</div>