<?php

declare(strict_types=1);

/** @var \GetResponse\GetResponseIntegration\Block\Admin\Webform $block */

use GetResponse\GetResponseIntegration\Helper\BlockPosition;
use GrShareCode\WebForm\WebForm;

$webForms = $block->getWebForms();
$webformSettings = $block->getWebFormSettings();
?>

<form method="post" action="<?php echo $block->getUrlWithScope('getresponse/webform/save'); ?>">
    <?php echo $block->getBlockHtml('formkey'); ?>

    <div class="page-main-actions">
        <?php require('switch_scope.phtml') ?>
        <div class="page-main-hint">
            <span>Add forms (or exit popups) to your store. Get new contacts when your customers fill them out.</span>
        </div>
        <div class="page-actions">
            <div class="page-actions-inner">
                <div class="page-actions-buttons">
                    <button id="export" title="Export" type="submit" class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button" aria-disabled="false">
                        <span class="ui-button-text">
                            <span>Save</span>
                        </span>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div id="page:main-container" class="page-columns">
        <div class="admin__old">
            <div id="container" class="main-col">
                <fieldset class="fieldset admin__fieldset no-display" id="publish_fieldset" style="display: block;">
                    <div class="admin__field field field-basic_publish required _required">
                        <label class="label admin__field-label" for="publish"></label>
                        <div class="admin__field-control control">
                            <div class="admin__field admin__field-option publish__field">
                                <input id="publish" name="isEnabled" class="admin__control-checkbox" type="checkbox" value="1"
                                    <?php if ($webformSettings->isEnabled()):?>
                                        checked="checked"
                                    <?php endif ?>
                                >
                                <label class="admin__field-label" for="publish">Add contacts to GetResponse via forms (or exit popups)</label>
                            </div>
                        </div>
                    </div>
                    <div class="admin__field field field-basic_webform required _required forms <?php if (!$webformSettings->isEnabled()):?>hidden<?php endif ?>">
                        <label class="label admin__field-label" for="webform_id">
                            <span>Form</span>
                        </label>
                        <div class="admin__field-control control">
                            <div class="admin__field">
                                <select name="webformId" id="webform_id" class="select admin__control-select" aria-required="true">
                                    <option value="">Select a form you want to display</option>
                                    <?php if ($webForms !== null):?>
                                        <?php
                                        /** @var WebForm $form */
                                        foreach ($webForms as $form): ?>
                                            <option
                                                value="<?php echo $form->getWebFormId()?>"
                                                data-url="<?php echo $form->getScriptUrl()?>"
                                                <?php if($webformSettings->getWebformId() === $form->getWebFormId()):?>
                                                    selected="selected"
                                                <?php endif ?>
                                            ><?php echo $form->getName() ?></option>
                                        <?php endforeach ?>
                                    <?php else: ?>
                                        <option value="" disabled="disabled">No forms</option>
                                    <?php endif ?>
                                </select>
                                <input type="hidden" value="" name="url" id="webform_url" />
                            </div>
                        </div>
                    </div>
                    <div class="admin__field field field-basic_sidebar required _required forms <?php if (!$webformSettings->isEnabled()):?>hidden<?php endif ?>">
                        <label class="label admin__field-label" for="sidebar">
                            <span>Block position</span>
                        </label>
                        <div class="admin__field-control control">
                            <div class="admin__field">
                                <select name="sidebar" class="select admin__control-select" aria-required="true">
                                    <option value="">Select where to place the form</option>
                                    <?php foreach (BlockPosition::POSITIONS as $position => $name):?>
                                        <option
                                            value="<?php echo $position ?>"
                                            <?php if ($webformSettings->getSidebar() === $position): ?>
                                                selected="selected"
                                            <?php endif ?>
                                        ><?php echo $name ?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
    </div>
</form>

<script>
    require(['webform']);
</script>